### ISSUE TITLE
Pointer vers une instance de PostgreSQL

### ISSUE THREAD

**Issue by cl-parsons** [TiBillet/Lespass#10]
Dans la documentation ( https://tibillet.org/fr/docs/install/docker_install/#lespass--multi-tenant-engine-for-membership-ticketing-and-online-cashless-refill ), le fichier ".env" doit être peuplé par une variable "POSTGRES_HOST". Cette variable n'est pas prise en compte par le fichier "settings.py" de l'instance de Django, elle est simplement écrise en dur et doit être éditée à la main dans le cas ou notre instance Postgres n'est pas joignable par le hostname "postgres".

**Comment by Nasjoe** [comment]
https://github.com/TiBillet/Lespass/commit/5a61e824933062668a357dff1612056b472a7b02
