### ISSUE TITLE
Impossible de configurer un serveur SMTP sans authentification

### ISSUE THREAD

**Issue by cl-parsons** [TiBillet/Lespass#14]
https://github.com/TiBillet/Lespass/blob/31222186ca643f73930562f1b6bcd99b3d77925e/BaseBillet/tasks.py#L64

Pour avoir une configuration mail valide, on est forcé d'avoir une valeur de EMAIL_USER et EMAIL_PASSWORD. Lorsque notre serveur mail tourne sans authentification (typiquement le cas lors de l'utilsation d'un serveur mail local), on est bloqué à ce stade là et on ne peut pas créer de compte.

**Comment by cl-parsons** [comment]
Comme spécifié dans la documentation de Django, EMAIL_HOST_USER et EMAIL_HOST_PASSWORD sont optionnels.

Par contre, assigner par défault le "from_email" à EMAIL_HOST_USER n'est vraiment pas une bonne idée. Je mettrais plutôt un EMAIL_FROM_USER comme configuration pour permettre de mettre une adresse non existante (type no-reply@domain.tld) et non pas une adresse existance et loggée. Celà évitera pas mal de spam potentiel au cas où le serveur mail est ouvert vers l'extérieur, et permet aussi de cacher le login sur le serveur SMTP.

**Comment by Nasjoe** [comment]
Oui, c'est une question qui était noté comme a régler, comme le dit le TODO linge 79 :)
J'avais codé un truc qui vérifie les domaines en autre pour cette raison.

Je suis preneur d'une solution avec un serveur local !
Ça serait bien utile pour l'env de dev', en effet :)

**Comment by Nasjoe** [comment]
Merci pour la remontée ! 
Hésite pas à me dire si ça te va : https://github.com/TiBillet/Lespass/commit/8d719cc89f13d38117aec0873a4c97f8bfb68d92
